<?php
declare(strict_types=1);
/** @var YoulagExtension $this */
?>

<div class="youlag-extension-settings-container">

  <form class="youlag-extension-settings-form" action="<?php echo _url('extension', 'configure', 'e', urlencode($this->getName())); ?>" method="post">
    <input type="hidden" name="_csrf" value="<?php echo FreshRSS_Auth::csrfToken(); ?>" />

    <h2>Youlag settings</h2>

    <section class="youlag-form-section">

      <h3>Default video playback source</h3>

      <div class="form-group">

        <div class="group-controls">

          <div class="yl-form-group--radio">
            <div class="form-group">
              <div class="yl-form-group--radio-input-container">
                <label for="youlag_playback_youtube">YouTube</label>
                <div class="yl-form-control-radio-input">
                  <input type="radio" id="youlag_playback_youtube" name="yl_indivious_enabled" value="0" 
                    <?= !$this->isInvidiousEnabled() ? 'checked="checked"' : '' ?>
                  >
                  <div class="group-controls">
                    <input type="text" value="https://youtube.com" data-leave-validation="1" readonly>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div class="yl-form-group--radio">
            <div class="form-group">
              <div class="yl-form-group--radio-input-container">
                <label for="youlag_playback_invidious">Invidious</label>
                <div class="yl-form-group-help">The base URL of the Invidious instance.</div>
                <div class="yl-form-control-radio-input">
                  <input type="radio" id="youlag_playback_invidious" name="yl_indivious_enabled" value="1" 
                    <?= $this->isInvidiousEnabled() ? 'checked="checked"' : '' ?>
                  >
                  <div class="group-controls">
                    <input type="text" id="yl_invidious_url_1" name="yl_invidious_url_1" placeholder="https://" value="<?php echo FreshRSS_Context::$user_conf->yl_invidious_url_1; ?>" data-leave-validation="1" <?= $this->isInvidiousEnabled() ? 'required' : '' ?>>
                  </div>
                </div>
              </div>
            </div>
            
          </div>

        </div>
      </div>





    </section>

    <div class="form-group form-actions">
      <div class="group-controls">
        <button type="submit" class="btn btn-important">Submit</button>
        <button type="reset" class="btn">Cancel</button>

        <button id="youlag_check_updates" type="button" class="btn">Check for updates (Github)</button>
      </div>
    </div>
  </form>

</div>