<?php
declare(strict_types=1);
/** @var YoulagExtension $this */
?>

<div class="yl-extension-settings-container" id="yl-settings-root">

  <form class="yl-extension-settings-form" action="<?php echo _url('extension', 'configure', 'e', urlencode($this->getName())); ?>" method="post">
    <input type="hidden" name="_csrf" value="<?php echo FreshRSS_Auth::csrfToken(); ?>" />

    <h2>Youlag settings</h2>

    <section class="yl-form-section">
      <?php
      $categories = isset($_SESSION['ext_categories']) ? $_SESSION['ext_categories'] : array();
      ?>

      <h3>Appearance</h3>

      <h4 class="mb-0">
        Pages and categories
        <div class="yl-form-group-help">
          Select the pages and categories whose feeds will be displayed in Youlag's video interface.
        </div>
      </h4>
      <?php if (!empty($categories)): ?>
        <div class="yl-form-category-container">
          <?php $whitelist = $this->getCategoryWhitelist(); ?>
          <!-- Place checkbox outside of label to utilize the checked="checked" state for visual statemanagement via css. -->
          <input id="yl_category_all" type="checkbox" name="yl_category_whitelist[]" value="all"
            <?php echo (empty($whitelist) || in_array('all', $whitelist)) ? ' checked="checked"' : ''; ?>>
          <label for="yl_category_all" class="inline-block">
            All pages and categories
          </label>
          <div class="yl-form-category-subitem-container">
            <hr>
            <label>
              <input type="checkbox" name="yl_category_whitelist[]" value="home"
                <?php echo in_array('home', $whitelist) ? ' checked="checked"' : ''; ?>>
              Subscriptions
            </label>
            <label>
              <input type="checkbox" name="yl_category_whitelist[]" value="important"
                <?php echo in_array('important', $whitelist) ? ' checked="checked"' : ''; ?>>
              Important
            </label>
            <label>
              <input type="checkbox" name="yl_category_whitelist[]" value="watch_later"
                <?php echo in_array('watch_later', $whitelist) ? ' checked="checked"' : ''; ?>>
                <span class="yl-form-category__original-label">Favorites</span>
                <span class="yl-form-category__video-label">Watch later</span>
            </label>
            <label>
              <input type="checkbox" name="yl_category_whitelist[]" value="playlists"
                <?php echo in_array('playlists', $whitelist) ? ' checked="checked"' : ''; ?>>
                <span class="yl-form-category__original-label">My Labels</span>
                <span class="yl-form-category__video-label">Playlists</span>
            </label>
            <?php foreach ($categories as $cat): ?>
              <?php $catId = (string)$cat->id(); ?>
              <label>
                <input
                  type="checkbox"
                  name="yl_category_whitelist[]"
                  value="<?php echo 'c_' . htmlspecialchars($catId); ?>"
                  <?php echo in_array('c_' . $catId, $whitelist) ? ' checked="checked"' : ''; ?>>
                <?php echo htmlspecialchars((string)$cat->name()); ?>
              </label>
            <?php endforeach; ?>
          </div>
        </div>
      <?php else: ?>
        <div class="yl-form-group-help">No categories found.</div>
      <?php endif; ?>

      <h4 class="mb-0">
        Labels
      </h4>
      <label for="yl_video_labels_enabled" class="flex">
        <input type="checkbox" id="yl_video_labels_enabled" name="yl_video_labels_enabled" value="1" class="mb-auto"
          <?php echo (FreshRSS_Context::$user_conf->yl_video_labels_enabled === null || FreshRSS_Context::$user_conf->yl_video_labels_enabled) ? ' checked="checked"' : ''; ?>>
        <div class="inline-block">
          Use video platform labels
          <div class="yl-form-group-help">
            Renames "Favorites → Watch later", "My Tags → Playlists".
          </div>
        </div>
      </label>
    </section>
    <section class="yl-form-section">
      <h3>Feeds</h3>

      <h4 class="mb-0">
        YouTube shorts
      </h4>
      <label for="yl_block_youtube_shorts" class="flex">
        <input type="checkbox" id="yl_block_youtube_shorts" name="yl_block_youtube_shorts" value="1" class="mb-auto"
          <?php echo (FreshRSS_Context::$user_conf->yl_block_youtube_shorts) ? ' checked="checked"' : ''; ?>>
        <div class="inline-block">
          Block incoming YouTube shorts
          <div class="yl-form-group-help">
            Existing shorts in your feeds will not be affected.
          </div>
        </div>
      </label>
    </section>
    <section class="yl-form-section">

      <h3>Default video playback source</h3>

      <div class="form-group">

        <div class="group-controls">

          <div class="yl-form-group--radio">
            <div class="form-group">
              <div class="yl-form-group--radio-input-container">
                <label for="yl_playback_youtube">YouTube</label>
                <div class="yl-form-control-radio-input">
                  <input type="radio" id="yl_playback_youtube" name="yl_invidious_enabled" value="0" 
                    <?= !$this->isInvidiousEnabled() ? 'checked="checked"' : '' ?>
                  >
                  <div class="group-controls">
                    <input type="text" value="https://youtube.com" data-leave-validation="1" readonly>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div class="yl-form-group--radio">
            <div class="form-group">
              <div class="yl-form-group--radio-input-container">
                <label for="yl_playback_invidious">Invidious</label>
                <div class="yl-form-group-help">The base URL of the Invidious instance.</div>
                <div class="yl-form-control-radio-input">
                  <input type="radio" id="yl_playback_invidious" name="yl_invidious_enabled" value="1" 
                    <?= $this->isInvidiousEnabled() ? 'checked="checked"' : '' ?>
                  >
                  <div class="group-controls">
                    <input type="text" id="yl_invidious_url_1" name="yl_invidious_url_1" placeholder="https://" value="<?php echo FreshRSS_Context::$user_conf->yl_invidious_url_1; ?>" data-leave-validation="1">
                  </div>
                </div>
              </div>
            </div>
            
          </div>

        </div>
      </div>

    </section>

    <div class="form-group form-actions">
      <div class="group-controls">
        <button type="submit" class="btn btn-important">Submit</button>
        <button type="reset"  class="btn">Cancel</button>

        <a id="yl_check_updates" href="https://github.com/civilblur/youlag/releases" target="_blank" rel="noopener noreferrer" class="btn">Check for updates (Github)</a>
      </div>
    </div>
  </form>

</div>